### ISSUE TITLE
Numpy, Matplotlib, and Cartopy Basics Notebook Feedback

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/pyaos-ams-2020#24]
@mwilson14 - great job! It's a lot of ground to cover, and I think you've hit the right points. It will all come down to timing, which of course is super hard to know from just looking at a notebook. I'd be happy to chat in Boston to get a better feel. Right now it's about 50 seconds per executable cell. Given the overall time constraints, this whole workshop will give participants quite the `Shift-Enter` workshop :-)

Outside of timing, one question I had was about the tornado reports (love the mapping section, btw). For the tornado reports, did you pull those from SPC? Soon Siphon will have an easy way to grab them from there, but not quite yet.

**Comment by mwilson14** [comment]
Yep, the tornado reports are from SPC! I'll add a link to the data source and streamline the rest of the script a bit later today. I practiced running through it and it took about 23 minutes, so it's cutting it a bit close.
