### ISSUE TITLE
Classic notebook server vs lab

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/pyaos-ams-2020#30]
@jthielen brought up a good point over dinner that we are currently using the classic Jupiter notebook interface, but we could use the lab interface with a simple edit of the url (just add /lab to the file browser url). Thoughts? I seem to remember hearing there was an issue with JuoyterHub and the lab interface, but I cannot remember, and it seems that’s not the case. Lab is more likely what participants would be using on their own machines, so maybe it’s a good idea to change it over right at the beginning with a one time url edit?

@julienchastang - do you recall anything about classic vs lab?

**Comment by julienchastang** [comment]
My aim was to have as minimal a set up as possible. Basically, fewer moving parts the better. But as @jthielen figured out, lab is installed anyway. This is sort of inadvertent and inherited from previous setups. At this point, if you feel more comfortable presenting in lab, go ahead. Yes, all you need to do is add the `/lab` suffix.
